### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by javitocor**
In this final project working for HTML and CSS I had to create a conference/event webpage.
In this project, we can find 3 pages (index, about and tickets) responsive with a breakpoint at 768px.
I have used box model, flexbox and grid to complete all three pages.
The project has passed the validator check and the sticklers report no issue.

### CODE REVIEW

**Comment by lekegitrepo** [comment]
This PR is under Review by **[TSE] Temitayo Adeleke**

**Comment by lekegitrepo** [comment]
**Hi @javitocor** :clap: :clap: :clap:
You have done an excellent work here (I'm not flattering) but you still need to make a little modification by specifically naming your grid classes. Make the following required changes and consider the optional suggestions if you want to:
 **_Required:_**
1. Classes to define columns sized from 1/12th of the row to 100% of the row ( [Odin](https://www.theodinproject.com/courses/html5-and-css3/lessons/design-your-own-grid-based-framework))
12_column_grid_requirement

2. The defined columns should have breakpoints (example column-large-2) ([Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59564673/)) it will be a good practice to give the classes conventional names (like col-md-4) that define the grids
breakpoints_requirement

**_As mentioned in the Requirements:_**
##### Breakpoints
* [ ] The CSS files should define a breakpoint for small screens with a width of up to 720px ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/grid_based_framework/small_breakpoint_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59564673/))
* [ ] The CSS files should define a breakpoint for medium screens with a width in the range of 720px - 1024px ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/grid_based_framework/medium_breakpoint_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59564673/))
* [ ] The CSS files should define a breakpoint for large screens with width above 1024px ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/grid_based_framework/large_breakpoint_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59564673/))

### _Optional:_
### Box utilities

#### Margins

* [ ] The CSS files define separate classes for margin top, bottom, left, right, all margins and auto
* [ ] The margins should span from `0 rem` to `1 rem`
* [ ] The margins should have breakpoints (e.g. margin-sm-top-1)

#### Padding

* [ ] The CSS files define separate classes for padding top, bottom, left, right, all padding and auto
* [ ] The padding should span from `0 rem` to `1 rem`
* [ ] The padding should have breakpoints (example padding-lg-2)

### Positioning

#### Floats

* [ ] The CSS files define separate classes for float left, right and clearing the floats

#### Positions

* [ ] The CSS files define separate classes to change the position property of an element to relative, absolute or fixed

### Display

#### Display properties

The CSS files define:

* [ ] A class to set the display property of an element to flex
* [ ] A class to set the display property to hidden
* [ ] A class to set the display property to none
* [ ] The none class should have breakpoints (example display-md-none)

#### Flex properties

The CSS files define:

* [ ] Classes to set vertical alignment as top, bottom or center
* [ ] Classes to set horizontal alignment as left, right or center

### Colors

#### Background and text

The CSS files define:

* [ ] At least ten different classes to set the background and text colors of an element

### Text

#### Utilities

The CSS files define:

* [ ] Classes to horizontally align text to the left, right or center
* [ ] At least five classes to set the font size of an element
* [ ] Three classes to set the font weight of an element (bold, normal, medium)

#### Border

* [ ] The CSS files define separate classes for border top, bottom, left, right, all border
* [ ] The border should span from 0 to 1rem
* [ ] The border should have classes for making box round
* [ ] The border should have a class defined to transform a box into a circle

If you have any doubt or question contact me on slack.

**_Kindly make the required changes and resubmit for review._**
**Reviewed by:** **_Temitayo Adeleke_**

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
## Status: Requires Changes

**Comment by javitocor** [comment]
In this final project working for HTML and CSS I had to create a conference/event webpage.
In this project, we can find 3 pages (index, about and tickets) responsive with breakpoints at 768px and 550px.
I have used box model, flexbox and grid to complete all three pages.
After the first review, I have changed the presentation video and added the second breakpoint to make it fully responsive.
The project has passed the validator check and the sticklers report no issue.
As the previous reviewer took the requirements from another project the basic requirements for this project you can find it here: https://www.notion.so/HTML-CSS-capstone-project-Conference-page-ed3efca4b9824484a9df7f9f24067ff7

**Comment by SofiBretz** [comment]
### Changes required ♻️
### Hello! 🌟

Great work on this project, but you need to fix the issues below before moving on ⬇️

- [ ] It’s better to delete commented code on your HTML and CSS file.  [Here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/) you can see the information about this.
COMMENTLINE

- [ ] Pull Request has a meaningful title and a short description, [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/
) you can learn about it. 

[OPTIONAL]

- [ ] Consider adding a screenshot of your project and the demo link in your readme file.

_**After making the required changes please submit a new code review request**_
Good luck! 🍀 You are almost there! 💪

SofiBretz.

**Comment by javitocor** [comment]
In this final project working for HTML and CSS I had to create a conference/event webpage.
In this project, we can find 3 pages (index, about and tickets) responsive with breakpoints at 768px and 550px.
I have used box model, flexbox and grid to complete all three pages.
After the first review, I have changed the presentation video and added the second breakpoint to make it fully responsive.
The project has passed the validator check and the sticklers report no issue.
As the previous reviewer took the requirements from another project the basic requirements for this project you can find it here: https://www.notion.so/HTML-CSS-capstone-project-Conference-page-ed3efca4b9824484a9df7f9f24067ff7

**Comment by uryelah** [comment]
Hello **Javier Correas Sanchez Cuesta**, I'm Sarah, the last reviwer for this PR . ✌️ 

You did a great job completing all the required changes from the last reviews, congrats! 👏 👏 

----

### Your project is approved! 🎊 🎉  💛 
### 

**You may close this Pull Request and merge the changes**

-----

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Pull request merged**
